all: presentacion1.tex presentacion2.tex

presentacion1: presentacion1.tex
	pdflatex presentacion2.tex

presentacion2: presentacion2.tex
	pdflatex presentacion2.tex

clean:
	rm -rf presentacion*.aux presentacion*.log presentacion*.pdf presentacion*.nav presentacion*.out presentacion*.snm presentacion*.toc
